# Generated by Django 4.1.4 on 2022-12-17 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=200)),
                ('item_date', models.DateTimeField(verbose_name='date published')),
                ('item_price', models.IntegerField(default=0)),
                ('item_description', models.CharField(max_length=200)),
                ('item_image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
