# Generated by Django 4.1.4 on 2022-12-17 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_likes',
            field=models.IntegerField(default=0),
        ),
    ]
